[package]
name = "copyrighter"
version = "0.1.0"
authors = ["Matt Kline <matthew.kline@flukenetworks.com>"]

[dependencies]
git-historian = { git = "https://github.com/mrkline/git-historian.git" }
getopts = "0.2"
time = "0.1"
threadpool = "1.3"
num_cpus = "0.2.13"
regex = "0.1"
lazy_static = "0.1"
libc = "0.2"
